---
- hosts: 127.0.0.1
  gather_facts: true
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    xdg_config_home: "{{ home }}/.config"
    xdg_data_home: "{{ home }}/.local/share"
    xdg_state_home: "{{ home }}/.local/state"
    xdg_cache_home: "{{ home }}/.cache"

  tasks:
  - name: allow comments at the CLI
    ansible.builtin.shell: setopt interactive_comments
    args:
      executable: /bin/zsh
  
  - name: xdg directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
    loop:
      - "{{ xdg_config_home }}"
      - "{{ xdg_data_home }}"
      - "{{ xdg_state_home }}"
      - "{{ xdg_cache_home }}"

  - name: zdot directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
    loop:
      - "{{ xdg_config_home }}/zsh"
      - "{{ xdg_config_home }}/zsh/config.d" 
      - "{{ xdg_state_home }}/zsh"

  - name: bootstrap .zshenv
    ansible.builtin.copy:
      src: "./files/zshenv"
      dest: "{{ home }}/.zshenv"

  - name: stub zdot .zshenv file
    ansible.builtin.copy:
      dest: "{{ xdg_config_home }}/zsh/.zshenv"
      content: "# set common PATH variable"

  - name: bootstrap .zprofile
    ansible.builtin.copy:
      src: "./files/zprofile"
      dest: "{{ xdg_config_home }}/zsh/.zprofile"

  - name: bootstrap .zshrc
    ansible.builtin.copy:
      src: "./files/zshrc"
      dest: "{{ xdg_config_home }}/zsh/.zshrc"

  - name: vim xdg-compliant directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
    loop:
      - "{{ xdg_config_home }}/vim"
      - "{{ xdg_state_home }}/vim"
      - "{{ xdg_state_home }}/vim/swap"
      - "{{ xdg_state_home }}/vim/backup"
      - "{{ xdg_state_home }}/vim/undo"
      - "{{ xdg_data_home }}/vim"
      - "{{ xdg_data_home }}/vim/after"

  - name: vimrc
    ansible.builtin.copy:
      src: "./files/vimrc"
      dest: "{{ xdg_config_home }}/vim/vimrc"

  - name: vim xdg-compliant settings
    ansible.builtin.copy:
      src: "./files/20_vim.zsh"
      dest: "{{ xdg_config_home }}/zsh/config.d/20_vim.zsh"
